spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spscrmdb?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    platform: mysql
    test-while-idle: true
    validation-query: SELECT 1
    test-on-borrow: true
    dbcp:
      min-idle: 5
      max-idle: 10
      max-active: 20
      max-wait: 20000
      initial-size: 10
      remove-abandoned: true
      remove-abandoned-timeout: 10
      test-on-borrow: true
      validation-query: "select 1"
  jpa:
    show-sql: true